import { defaultStorage, leaflets } from "@/lib/catalog/leaflets";
import type { ConcernSlug, Form, Regimen, Schedule, Sku } from "@/lib/catalog/types";
import { packLabel } from "@/lib/format";

interface SkuFacts {
  slug: string;
  brand: string;
  molecule: string;
  strength: string;
  form: Form;
  packUnits: number;
  /** Overrides the derived pack label, e.g. "bottle of 120". */
  pack?: string;
  /** Printed MRP in paise. */
  mrp: number;
  schedule: Schedule;
  manufacturer: string;
  concerns: readonly ConcernSlug[];
  inStock?: boolean;
  regimen?: Regimen | null;
}

const formPhrase: Record<Form, string> = {
  tablet: "a tablet",
  "sr-tablet": "a sustained-release tablet",
  capsule: "a capsule",
  syrup: "a syrup",
  drops: "a solution",
  cream: "a cream",
  gel: "a gel",
  inhaler: "an inhaler",
  vial: "a vial",
  sachet: "a sachet",
  strip: "",
  device: "",
};

const facts: readonly SkuFacts[] = [
  // Diabetes
  {
    slug: "glycomet-500-sr",
    brand: "Glycomet 500 SR",
    molecule: "Metformin",
    strength: "500mg",
    form: "sr-tablet",
    packUnits: 20,
    mrp: 3650,
    schedule: "H",
    manufacturer: "USV",
    concerns: ["diabetes"],
  },
  {
    slug: "carbophage-sr-500",
    brand: "Carbophage SR 500",
    molecule: "Metformin",
    strength: "500mg",
    form: "sr-tablet",
    packUnits: 20,
    mrp: 3400,
    schedule: "H",
    manufacturer: "Merck",
    concerns: ["diabetes"],
  },
  {
    slug: "jan-aushadhi-metformin-500-sr",
    brand: "Jan Aushadhi Metformin 500 SR",
    molecule: "Metformin",
    strength: "500mg",
    form: "sr-tablet",
    packUnits: 10,
    mrp: 920,
    schedule: "H",
    manufacturer: "PMBJP",
    concerns: ["diabetes"],
  },
  {
    slug: "glycomet-850",
    brand: "Glycomet 850",
    molecule: "Metformin",
    strength: "850mg",
    form: "tablet",
    packUnits: 20,
    mrp: 4420,
    schedule: "H",
    manufacturer: "USV",
    concerns: ["diabetes"],
    inStock: false,
  },
  {
    slug: "glyciphage-850",
    brand: "Glyciphage 850",
    molecule: "Metformin",
    strength: "850mg",
    form: "tablet",
    packUnits: 10,
    mrp: 2350,
    schedule: "H",
    manufacturer: "Franco-Indian",
    concerns: ["diabetes"],
  },
  {
    slug: "gluformin-500",
    brand: "Gluformin 500",
    molecule: "Metformin",
    strength: "500mg",
    form: "tablet",
    packUnits: 20,
    mrp: 3280,
    schedule: "H",
    manufacturer: "Abbott",
    concerns: ["diabetes"],
  },
  {
    slug: "glyciphage-500",
    brand: "Glyciphage 500",
    molecule: "Metformin",
    strength: "500mg",
    form: "tablet",
    packUnits: 10,
    mrp: 1450,
    schedule: "H",
    manufacturer: "Franco-Indian",
    concerns: ["diabetes"],
  },
  {
    slug: "glycomet-gp-1",
    brand: "Glycomet GP 1",
    molecule: "Glimepiride + metformin",
    strength: "1mg + 500mg",
    form: "tablet",
    packUnits: 15,
    mrp: 9800,
    schedule: "H",
    manufacturer: "USV",
    concerns: ["diabetes"],
  },
  {
    slug: "gemer-1",
    brand: "Gemer 1",
    molecule: "Glimepiride + metformin",
    strength: "1mg + 500mg",
    form: "tablet",
    packUnits: 15,
    mrp: 10500,
    schedule: "H",
    manufacturer: "Sun Pharma",
    concerns: ["diabetes"],
  },
  {
    slug: "amaryl-1",
    brand: "Amaryl 1",
    molecule: "Glimepiride",
    strength: "1mg",
    form: "tablet",
    packUnits: 30,
    mrp: 16500,
    schedule: "H",
    manufacturer: "Sanofi",
    concerns: ["diabetes"],
  },
  {
    slug: "glimestar-1",
    brand: "Glimestar 1",
    molecule: "Glimepiride",
    strength: "1mg",
    form: "tablet",
    packUnits: 15,
    mrp: 6800,
    schedule: "H",
    manufacturer: "Mankind",
    concerns: ["diabetes"],
  },
  {
    slug: "galvus-50",
    brand: "Galvus 50",
    molecule: "Vildagliptin",
    strength: "50mg",
    form: "tablet",
    packUnits: 15,
    mrp: 32000,
    schedule: "H",
    manufacturer: "Novartis",
    concerns: ["diabetes"],
  },
  {
    slug: "zomelis-50",
    brand: "Zomelis 50",
    molecule: "Vildagliptin",
    strength: "50mg",
    form: "tablet",
    packUnits: 15,
    mrp: 19000,
    schedule: "H",
    manufacturer: "Alkem",
    concerns: ["diabetes"],
  },
  {
    slug: "accu-chek-active-strips",
    brand: "Accu-Chek Active strips",
    molecule: "Blood glucose test strips",
    strength: "",
    form: "strip",
    packUnits: 50,
    pack: "box of 50",
    mrp: 89900,
    schedule: "OTC",
    manufacturer: "Roche",
    concerns: ["diabetes"],
    regimen: null,
  },
  {
    slug: "onetouch-select-plus-strips",
    brand: "OneTouch Select Plus strips",
    molecule: "Blood glucose test strips",
    strength: "",
    form: "strip",
    packUnits: 50,
    pack: "box of 50",
    mrp: 105000,
    schedule: "OTC",
    manufacturer: "LifeScan",
    concerns: ["diabetes"],
    regimen: null,
  },
  {
    slug: "accu-chek-softclix-lancets",
    brand: "Accu-Chek Softclix lancets",
    molecule: "Lancets",
    strength: "",
    form: "device",
    packUnits: 100,
    pack: "box of 100",
    mrp: 24000,
    schedule: "OTC",
    manufacturer: "Roche",
    concerns: ["diabetes"],
    regimen: null,
  },

  // Blood pressure and heart
  {
    slug: "telma-40",
    brand: "Telma 40",
    molecule: "Telmisartan",
    strength: "40mg",
    form: "tablet",
    packUnits: 30,
    mrp: 11200,
    schedule: "H",
    manufacturer: "Glenmark",
    concerns: ["blood-pressure"],
  },
  {
    slug: "telsartan-40",
    brand: "Telsartan 40",
    molecule: "Telmisartan",
    strength: "40mg",
    form: "tablet",
    packUnits: 15,
    mrp: 15000,
    schedule: "H",
    manufacturer: "Dr. Reddy's",
    concerns: ["blood-pressure"],
  },
  {
    slug: "jan-aushadhi-telmisartan-40",
    brand: "Jan Aushadhi Telmisartan 40",
    molecule: "Telmisartan",
    strength: "40mg",
    form: "tablet",
    packUnits: 10,
    mrp: 1500,
    schedule: "H",
    manufacturer: "PMBJP",
    concerns: ["blood-pressure"],
  },
  {
    slug: "telma-am",
    brand: "Telma AM",
    molecule: "Telmisartan + amlodipine",
    strength: "40mg + 5mg",
    form: "tablet",
    packUnits: 15,
    mrp: 19000,
    schedule: "H",
    manufacturer: "Glenmark",
    concerns: ["blood-pressure"],
  },
  {
    slug: "telsartan-am",
    brand: "Telsartan AM",
    molecule: "Telmisartan + amlodipine",
    strength: "40mg + 5mg",
    form: "tablet",
    packUnits: 15,
    mrp: 17500,
    schedule: "H",
    manufacturer: "Dr. Reddy's",
    concerns: ["blood-pressure"],
  },
  {
    slug: "amlong-5",
    brand: "Amlong 5",
    molecule: "Amlodipine",
    strength: "5mg",
    form: "tablet",
    packUnits: 30,
    mrp: 6800,
    schedule: "H",
    manufacturer: "Micro Labs",
    concerns: ["blood-pressure"],
  },
  {
    slug: "amlodac-5",
    brand: "Amlodac 5",
    molecule: "Amlodipine",
    strength: "5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 5400,
    schedule: "H",
    manufacturer: "Zydus",
    concerns: ["blood-pressure"],
  },
  {
    slug: "jan-aushadhi-amlodipine-5",
    brand: "Jan Aushadhi Amlodipine 5",
    molecule: "Amlodipine",
    strength: "5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 700,
    schedule: "H",
    manufacturer: "PMBJP",
    concerns: ["blood-pressure"],
  },
  {
    slug: "ecosprin-75",
    brand: "Ecosprin 75",
    molecule: "Aspirin",
    strength: "75mg",
    form: "tablet",
    packUnits: 14,
    mrp: 950,
    schedule: "H",
    manufacturer: "USV",
    concerns: ["blood-pressure"],
  },
  {
    slug: "loprin-75",
    brand: "Loprin 75",
    molecule: "Aspirin",
    strength: "75mg",
    form: "tablet",
    packUnits: 14,
    mrp: 720,
    schedule: "H",
    manufacturer: "Unichem",
    concerns: ["blood-pressure"],
  },
  {
    slug: "atorva-10",
    brand: "Atorva 10",
    molecule: "Atorvastatin",
    strength: "10mg",
    form: "tablet",
    packUnits: 30,
    mrp: 14500,
    schedule: "H",
    manufacturer: "Zydus",
    concerns: ["blood-pressure"],
  },
  {
    slug: "atorlip-10",
    brand: "Atorlip 10",
    molecule: "Atorvastatin",
    strength: "10mg",
    form: "tablet",
    packUnits: 15,
    mrp: 9200,
    schedule: "H",
    manufacturer: "Cipla",
    concerns: ["blood-pressure"],
  },
  {
    slug: "jan-aushadhi-atorvastatin-10",
    brand: "Jan Aushadhi Atorvastatin 10",
    molecule: "Atorvastatin",
    strength: "10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 1150,
    schedule: "H",
    manufacturer: "PMBJP",
    concerns: ["blood-pressure"],
  },
  {
    slug: "rosuvas-10",
    brand: "Rosuvas 10",
    molecule: "Rosuvastatin",
    strength: "10mg",
    form: "tablet",
    packUnits: 15,
    mrp: 24500,
    schedule: "H",
    manufacturer: "Sun Pharma",
    concerns: ["blood-pressure"],
  },
  {
    slug: "rozavel-10",
    brand: "Rozavel 10",
    molecule: "Rosuvastatin",
    strength: "10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 17000,
    schedule: "H",
    manufacturer: "Sun Pharma",
    concerns: ["blood-pressure"],
  },
  {
    slug: "omron-hem-7120",
    brand: "Omron HEM-7120",
    molecule: "Blood pressure monitor",
    strength: "",
    form: "device",
    packUnits: 1,
    pack: "1 monitor with cuff",
    mrp: 185000,
    schedule: "OTC",
    manufacturer: "Omron",
    concerns: ["blood-pressure"],
    regimen: null,
  },

  // Thyroid
  {
    slug: "thyronorm-25",
    brand: "Thyronorm 25",
    molecule: "Levothyroxine",
    strength: "25mcg",
    form: "tablet",
    packUnits: 120,
    pack: "bottle of 120",
    mrp: 13000,
    schedule: "H",
    manufacturer: "Abbott",
    concerns: ["thyroid"],
  },
  {
    slug: "thyronorm-50",
    brand: "Thyronorm 50",
    molecule: "Levothyroxine",
    strength: "50mcg",
    form: "tablet",
    packUnits: 120,
    pack: "bottle of 120",
    mrp: 14200,
    schedule: "H",
    manufacturer: "Abbott",
    concerns: ["thyroid"],
  },
  {
    slug: "thyronorm-75",
    brand: "Thyronorm 75",
    molecule: "Levothyroxine",
    strength: "75mcg",
    form: "tablet",
    packUnits: 120,
    pack: "bottle of 120",
    mrp: 15200,
    schedule: "H",
    manufacturer: "Abbott",
    concerns: ["thyroid"],
    inStock: false,
  },
  {
    slug: "thyronorm-100",
    brand: "Thyronorm 100",
    molecule: "Levothyroxine",
    strength: "100mcg",
    form: "tablet",
    packUnits: 120,
    pack: "bottle of 120",
    mrp: 16000,
    schedule: "H",
    manufacturer: "Abbott",
    concerns: ["thyroid"],
  },
  {
    slug: "eltroxin-50",
    brand: "Eltroxin 50",
    molecule: "Levothyroxine",
    strength: "50mcg",
    form: "tablet",
    packUnits: 100,
    pack: "bottle of 100",
    mrp: 15200,
    schedule: "H",
    manufacturer: "GSK",
    concerns: ["thyroid"],
  },
  {
    slug: "eltroxin-100",
    brand: "Eltroxin 100",
    molecule: "Levothyroxine",
    strength: "100mcg",
    form: "tablet",
    packUnits: 100,
    pack: "bottle of 100",
    mrp: 17500,
    schedule: "H",
    manufacturer: "GSK",
    concerns: ["thyroid"],
  },
  {
    slug: "thyrox-25",
    brand: "Thyrox 25",
    molecule: "Levothyroxine",
    strength: "25mcg",
    form: "tablet",
    packUnits: 100,
    pack: "bottle of 100",
    mrp: 11800,
    schedule: "H",
    manufacturer: "Macleods",
    concerns: ["thyroid"],
  },
  {
    slug: "thyrox-75",
    brand: "Thyrox 75",
    molecule: "Levothyroxine",
    strength: "75mcg",
    form: "tablet",
    packUnits: 100,
    pack: "bottle of 100",
    mrp: 14400,
    schedule: "H",
    manufacturer: "Macleods",
    concerns: ["thyroid"],
  },

  // Skin and hair
  {
    slug: "tugain-5",
    brand: "Tugain 5%",
    molecule: "Minoxidil",
    strength: "5%",
    form: "drops",
    packUnits: 60,
    mrp: 89000,
    schedule: "OTC",
    manufacturer: "Cipla",
    concerns: ["skin-hair"],
  },
  {
    slug: "mintop-5",
    brand: "Mintop 5%",
    molecule: "Minoxidil",
    strength: "5%",
    form: "drops",
    packUnits: 60,
    mrp: 82000,
    schedule: "OTC",
    manufacturer: "Dr. Reddy's",
    concerns: ["skin-hair"],
  },
  {
    slug: "finax-1",
    brand: "Finax 1",
    molecule: "Finasteride",
    strength: "1mg",
    form: "tablet",
    packUnits: 30,
    mrp: 23000,
    schedule: "H",
    manufacturer: "Dr. Reddy's",
    concerns: ["skin-hair"],
  },
  {
    slug: "finpecia-1",
    brand: "Finpecia 1",
    molecule: "Finasteride",
    strength: "1mg",
    form: "tablet",
    packUnits: 15,
    mrp: 12000,
    schedule: "H",
    manufacturer: "Cipla",
    concerns: ["skin-hair"],
  },
  {
    slug: "candid-cream",
    brand: "Candid cream",
    molecule: "Clotrimazole",
    strength: "1%",
    form: "cream",
    packUnits: 20,
    mrp: 9500,
    schedule: "OTC",
    manufacturer: "Glenmark",
    concerns: ["skin-hair"],
  },
  {
    slug: "clocip-cream",
    brand: "Clocip cream",
    molecule: "Clotrimazole",
    strength: "1%",
    form: "cream",
    packUnits: 15,
    mrp: 6200,
    schedule: "OTC",
    manufacturer: "Cipla",
    concerns: ["skin-hair"],
  },
  {
    slug: "clindac-a-gel",
    brand: "Clindac A gel",
    molecule: "Clindamycin",
    strength: "1%",
    form: "gel",
    packUnits: 15,
    mrp: 16000,
    schedule: "H",
    manufacturer: "Galderma",
    concerns: ["skin-hair"],
  },
  {
    slug: "acnesol-gel",
    brand: "Acnesol gel",
    molecule: "Clindamycin",
    strength: "1%",
    form: "gel",
    packUnits: 20,
    mrp: 12500,
    schedule: "H",
    manufacturer: "Systopic",
    concerns: ["skin-hair"],
  },
  {
    slug: "benzac-ac-2-5",
    brand: "Benzac AC 2.5%",
    molecule: "Benzoyl peroxide",
    strength: "2.5%",
    form: "gel",
    packUnits: 20,
    mrp: 21000,
    schedule: "OTC",
    manufacturer: "Galderma",
    concerns: ["skin-hair"],
  },
  {
    slug: "persol-ac-2-5",
    brand: "Persol AC 2.5%",
    molecule: "Benzoyl peroxide",
    strength: "2.5%",
    form: "gel",
    packUnits: 30,
    mrp: 13000,
    schedule: "OTC",
    manufacturer: "Wallace",
    concerns: ["skin-hair"],
    inStock: false,
  },
  {
    slug: "betnovate-cream",
    brand: "Betnovate cream",
    molecule: "Betamethasone valerate",
    strength: "0.1%",
    form: "cream",
    packUnits: 20,
    mrp: 4500,
    schedule: "H",
    manufacturer: "GSK",
    concerns: ["skin-hair"],
  },
  {
    slug: "betamil-cream",
    brand: "Betamil cream",
    molecule: "Betamethasone valerate",
    strength: "0.1%",
    form: "cream",
    packUnits: 20,
    mrp: 3800,
    schedule: "H",
    manufacturer: "Zee Laboratories",
    concerns: ["skin-hair"],
  },

  // Sexual health
  {
    slug: "suhagra-50",
    brand: "Suhagra 50",
    molecule: "Sildenafil",
    strength: "50mg",
    form: "tablet",
    packUnits: 4,
    mrp: 9000,
    schedule: "H",
    manufacturer: "Cipla",
    concerns: ["sexual-health"],
  },
  {
    slug: "manforce-50",
    brand: "Manforce 50",
    molecule: "Sildenafil",
    strength: "50mg",
    form: "tablet",
    packUnits: 4,
    mrp: 13500,
    schedule: "H",
    manufacturer: "Mankind",
    concerns: ["sexual-health"],
  },
  {
    slug: "tadalis-10",
    brand: "Tadalis 10",
    molecule: "Tadalafil",
    strength: "10mg",
    form: "tablet",
    packUnits: 4,
    mrp: 18000,
    schedule: "H",
    manufacturer: "Ajanta",
    concerns: ["sexual-health"],
    inStock: false,
  },
  {
    slug: "megalis-10",
    brand: "Megalis 10",
    molecule: "Tadalafil",
    strength: "10mg",
    form: "tablet",
    packUnits: 4,
    mrp: 21000,
    schedule: "H",
    manufacturer: "Macleods",
    concerns: ["sexual-health"],
  },
  {
    slug: "duralast-30",
    brand: "Duralast 30",
    molecule: "Dapoxetine",
    strength: "30mg",
    form: "tablet",
    packUnits: 4,
    mrp: 26000,
    schedule: "H",
    manufacturer: "Sun Pharma",
    concerns: ["sexual-health"],
  },
  {
    slug: "sustinex-30",
    brand: "Sustinex 30",
    molecule: "Dapoxetine",
    strength: "30mg",
    form: "tablet",
    packUnits: 4,
    mrp: 22000,
    schedule: "H",
    manufacturer: "Emcure",
    concerns: ["sexual-health"],
  },
  {
    slug: "forcan-150",
    brand: "Forcan 150",
    molecule: "Fluconazole",
    strength: "150mg",
    form: "tablet",
    packUnits: 1,
    mrp: 3000,
    schedule: "H",
    manufacturer: "Cipla",
    concerns: ["sexual-health", "skin-hair"],
  },
  {
    slug: "flucos-150",
    brand: "Flucos 150",
    molecule: "Fluconazole",
    strength: "150mg",
    form: "tablet",
    packUnits: 1,
    mrp: 2800,
    schedule: "H",
    manufacturer: "FDC",
    concerns: ["sexual-health", "skin-hair"],
  },

  // Mind and sleep
  {
    slug: "nexito-10",
    brand: "Nexito 10",
    molecule: "Escitalopram",
    strength: "10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 9500,
    schedule: "H",
    manufacturer: "Sun Pharma",
    concerns: ["mind-sleep"],
  },
  {
    slug: "stalopam-10",
    brand: "Stalopam 10",
    molecule: "Escitalopram",
    strength: "10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 8600,
    schedule: "H",
    manufacturer: "Lupin",
    concerns: ["mind-sleep"],
    inStock: false,
  },
  {
    slug: "nexito-5",
    brand: "Nexito 5",
    molecule: "Escitalopram",
    strength: "5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 6200,
    schedule: "H",
    manufacturer: "Sun Pharma",
    concerns: ["mind-sleep"],
  },
  {
    slug: "stalopam-5",
    brand: "Stalopam 5",
    molecule: "Escitalopram",
    strength: "5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 5500,
    schedule: "H",
    manufacturer: "Lupin",
    concerns: ["mind-sleep"],
  },
  {
    slug: "serta-50",
    brand: "Serta 50",
    molecule: "Sertraline",
    strength: "50mg",
    form: "tablet",
    packUnits: 10,
    mrp: 11000,
    schedule: "H",
    manufacturer: "Intas",
    concerns: ["mind-sleep"],
  },
  {
    slug: "daxid-50",
    brand: "Daxid 50",
    molecule: "Sertraline",
    strength: "50mg",
    form: "tablet",
    packUnits: 10,
    mrp: 15500,
    schedule: "H",
    manufacturer: "Pfizer",
    concerns: ["mind-sleep"],
  },
  {
    slug: "meloset-3",
    brand: "Meloset 3",
    molecule: "Melatonin",
    strength: "3mg",
    form: "tablet",
    packUnits: 10,
    mrp: 13000,
    schedule: "OTC",
    manufacturer: "Aristo",
    concerns: ["mind-sleep"],
  },
  {
    slug: "zolfresh-10",
    brand: "Zolfresh 10",
    molecule: "Zolpidem",
    strength: "10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 16000,
    schedule: "H1",
    manufacturer: "Abbott",
    concerns: ["mind-sleep"],
  },
  {
    slug: "nitrest-10",
    brand: "Nitrest 10",
    molecule: "Zolpidem",
    strength: "10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 12500,
    schedule: "H1",
    manufacturer: "Sun Pharma",
    concerns: ["mind-sleep"],
  },

  // Periods and women's health
  {
    slug: "meftal-spas",
    brand: "Meftal-Spas",
    molecule: "Mefenamic acid + dicyclomine",
    strength: "250mg + 10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 4200,
    schedule: "H",
    manufacturer: "Blue Cross",
    concerns: ["periods"],
  },
  {
    slug: "mefkind-spas",
    brand: "Mefkind-Spas",
    molecule: "Mefenamic acid + dicyclomine",
    strength: "250mg + 10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 3800,
    schedule: "H",
    manufacturer: "Mankind",
    concerns: ["periods"],
  },
  {
    slug: "folvite-5",
    brand: "Folvite 5",
    molecule: "Folic acid",
    strength: "5mg",
    form: "tablet",
    packUnits: 30,
    mrp: 3600,
    schedule: "OTC",
    manufacturer: "Pfizer",
    concerns: ["periods"],
  },
  {
    slug: "jan-aushadhi-folic-acid-5",
    brand: "Jan Aushadhi Folic Acid 5",
    molecule: "Folic acid",
    strength: "5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 450,
    schedule: "OTC",
    manufacturer: "PMBJP",
    concerns: ["periods"],
  },
  {
    slug: "evion-400",
    brand: "Evion 400",
    molecule: "Vitamin E",
    strength: "400mg",
    form: "capsule",
    packUnits: 10,
    mrp: 3000,
    schedule: "OTC",
    manufacturer: "P&G Health",
    concerns: ["periods", "skin-hair"],
  },
  {
    slug: "i-pill",
    brand: "i-pill",
    molecule: "Levonorgestrel",
    strength: "1.5mg",
    form: "tablet",
    packUnits: 1,
    mrp: 11000,
    schedule: "OTC",
    manufacturer: "Piramal",
    concerns: ["periods"],
    regimen: null,
  },
  {
    slug: "unwanted-72",
    brand: "Unwanted 72",
    molecule: "Levonorgestrel",
    strength: "1.5mg",
    form: "tablet",
    packUnits: 1,
    mrp: 8000,
    schedule: "OTC",
    manufacturer: "Mankind",
    concerns: ["periods"],
    regimen: null,
  },
  {
    slug: "primolut-n",
    brand: "Primolut N",
    molecule: "Norethisterone",
    strength: "5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 6500,
    schedule: "H",
    manufacturer: "Bayer Zydus",
    concerns: ["periods"],
  },
  {
    slug: "regestrone-5",
    brand: "Regestrone 5",
    molecule: "Norethisterone",
    strength: "5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 5200,
    schedule: "H",
    manufacturer: "Torrent",
    concerns: ["periods"],
  },
  {
    slug: "pause-500",
    brand: "Pause 500",
    molecule: "Tranexamic acid",
    strength: "500mg",
    form: "tablet",
    packUnits: 10,
    mrp: 25000,
    schedule: "H",
    manufacturer: "Emcure",
    concerns: ["periods"],
  },
  {
    slug: "trapic-500",
    brand: "Trapic 500",
    molecule: "Tranexamic acid",
    strength: "500mg",
    form: "tablet",
    packUnits: 10,
    mrp: 24000,
    schedule: "H",
    manufacturer: "Cipla",
    concerns: ["periods"],
  },
  {
    slug: "orofer-xt",
    brand: "Orofer XT",
    molecule: "Ferrous ascorbate + folic acid",
    strength: "100mg + 1.5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 14500,
    schedule: "OTC",
    manufacturer: "Emcure",
    concerns: ["periods"],
  },
  {
    slug: "feronia-xt",
    brand: "Feronia XT",
    molecule: "Ferrous ascorbate + folic acid",
    strength: "100mg + 1.5mg",
    form: "tablet",
    packUnits: 10,
    mrp: 13500,
    schedule: "OTC",
    manufacturer: "Zuventus",
    concerns: ["periods"],
  },

  // Everyday health
  {
    slug: "dolo-650",
    brand: "Dolo 650",
    molecule: "Paracetamol",
    strength: "650mg",
    form: "tablet",
    packUnits: 15,
    mrp: 3100,
    schedule: "OTC",
    manufacturer: "Micro Labs",
    concerns: ["everyday"],
  },
  {
    slug: "calpol-650",
    brand: "Calpol 650",
    molecule: "Paracetamol",
    strength: "650mg",
    form: "tablet",
    packUnits: 15,
    mrp: 3000,
    schedule: "OTC",
    manufacturer: "GSK",
    concerns: ["everyday"],
  },
  {
    slug: "crocin-advance",
    brand: "Crocin Advance",
    molecule: "Paracetamol",
    strength: "500mg",
    form: "tablet",
    packUnits: 15,
    mrp: 3400,
    schedule: "OTC",
    manufacturer: "GSK",
    concerns: ["everyday"],
  },
  {
    slug: "paracip-500",
    brand: "Paracip 500",
    molecule: "Paracetamol",
    strength: "500mg",
    form: "tablet",
    packUnits: 10,
    mrp: 1250,
    schedule: "OTC",
    manufacturer: "Cipla",
    concerns: ["everyday"],
  },
  {
    slug: "cetzine",
    brand: "Cetzine",
    molecule: "Cetirizine",
    strength: "10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 2000,
    schedule: "OTC",
    manufacturer: "Dr. Reddy's",
    concerns: ["everyday"],
  },
  {
    slug: "okacet",
    brand: "Okacet",
    molecule: "Cetirizine",
    strength: "10mg",
    form: "tablet",
    packUnits: 10,
    mrp: 1800,
    schedule: "OTC",
    manufacturer: "Cipla",
    concerns: ["everyday"],
  },
  {
    slug: "allegra-120",
    brand: "Allegra 120",
    molecule: "Fexofenadine",
    strength: "120mg",
    form: "tablet",
    packUnits: 10,
    mrp: 21000,
    schedule: "H",
    manufacturer: "Sanofi",
    concerns: ["everyday"],
  },
  {
    slug: "histafree-120",
    brand: "Histafree 120",
    molecule: "Fexofenadine",
    strength: "120mg",
    form: "tablet",
    packUnits: 10,
    mrp: 14000,
    schedule: "H",
    manufacturer: "Mankind",
    concerns: ["everyday"],
  },
  {
    slug: "pan-40",
    brand: "Pan 40",
    molecule: "Pantoprazole",
    strength: "40mg",
    form: "tablet",
    packUnits: 15,
    mrp: 16500,
    schedule: "H",
    manufacturer: "Alkem",
    concerns: ["everyday"],
  },
  {
    slug: "pantocid-40",
    brand: "Pantocid 40",
    molecule: "Pantoprazole",
    strength: "40mg",
    form: "tablet",
    packUnits: 15,
    mrp: 15800,
    schedule: "H",
    manufacturer: "Sun Pharma",
    concerns: ["everyday"],
  },
  {
    slug: "digene",
    brand: "Digene",
    molecule: "Aluminium hydroxide + magnesium hydroxide + simethicone",
    strength: "",
    form: "tablet",
    packUnits: 10,
    mrp: 1500,
    schedule: "OTC",
    manufacturer: "Abbott",
    concerns: ["everyday"],
    regimen: null,
  },
  {
    slug: "gelusil-mps",
    brand: "Gelusil MPS",
    molecule: "Aluminium hydroxide + magnesium hydroxide + simethicone",
    strength: "",
    form: "tablet",
    packUnits: 10,
    mrp: 1800,
    schedule: "OTC",
    manufacturer: "Pfizer",
    concerns: ["everyday"],
    inStock: false,
    regimen: null,
  },
  {
    slug: "electral",
    brand: "Electral",
    molecule: "Oral rehydration salts",
    strength: "",
    form: "sachet",
    packUnits: 1,
    mrp: 2200,
    schedule: "OTC",
    manufacturer: "FDC",
    concerns: ["everyday"],
    regimen: null,
  },
  {
    slug: "prolyte-ors",
    brand: "Prolyte ORS",
    molecule: "Oral rehydration salts",
    strength: "",
    form: "sachet",
    packUnits: 1,
    mrp: 2000,
    schedule: "OTC",
    manufacturer: "Cipla",
    concerns: ["everyday"],
    regimen: null,
  },
  {
    slug: "becosules-z",
    brand: "Becosules Z",
    molecule: "B-complex + vitamin C + zinc",
    strength: "",
    form: "capsule",
    packUnits: 20,
    mrp: 4500,
    schedule: "OTC",
    manufacturer: "Pfizer",
    concerns: ["everyday"],
  },
  {
    slug: "becozinc",
    brand: "Becozinc",
    molecule: "B-complex + vitamin C + zinc",
    strength: "",
    form: "capsule",
    packUnits: 15,
    mrp: 3800,
    schedule: "OTC",
    manufacturer: "Dr. Reddy's",
    concerns: ["everyday"],
  },
  {
    slug: "shelcal-500",
    brand: "Shelcal 500",
    molecule: "Calcium carbonate + vitamin D3",
    strength: "500mg + 250 IU",
    form: "tablet",
    packUnits: 15,
    mrp: 11500,
    schedule: "OTC",
    manufacturer: "Torrent",
    concerns: ["everyday"],
  },
  {
    slug: "jan-aushadhi-calcium-d3",
    brand: "Jan Aushadhi Calcium + D3",
    molecule: "Calcium carbonate + vitamin D3",
    strength: "500mg + 250 IU",
    form: "tablet",
    packUnits: 15,
    mrp: 2100,
    schedule: "OTC",
    manufacturer: "PMBJP",
    concerns: ["everyday"],
  },
  {
    slug: "limcee-500",
    brand: "Limcee 500",
    molecule: "Ascorbic acid",
    strength: "500mg",
    form: "tablet",
    packUnits: 15,
    mrp: 2500,
    schedule: "OTC",
    manufacturer: "Abbott",
    concerns: ["everyday"],
  },
  {
    slug: "celin-500",
    brand: "Celin 500",
    molecule: "Ascorbic acid",
    strength: "500mg",
    form: "tablet",
    packUnits: 15,
    mrp: 3000,
    schedule: "OTC",
    manufacturer: "GSK",
    concerns: ["everyday"],
  },
  {
    slug: "betadine-ointment",
    brand: "Betadine ointment",
    molecule: "Povidone iodine",
    strength: "5%",
    form: "cream",
    packUnits: 15,
    mrp: 10500,
    schedule: "OTC",
    manufacturer: "Win-Medicare",
    concerns: ["everyday"],
    regimen: null,
  },
  {
    slug: "cipladine-ointment",
    brand: "Cipladine ointment",
    molecule: "Povidone iodine",
    strength: "5%",
    form: "cream",
    packUnits: 20,
    mrp: 8000,
    schedule: "OTC",
    manufacturer: "Cipla",
    concerns: ["everyday"],
    regimen: null,
  },
  {
    slug: "volini-gel",
    brand: "Volini gel",
    molecule: "Diclofenac diethylamine + linseed oil + methyl salicylate + menthol",
    strength: "1.16%",
    form: "gel",
    packUnits: 30,
    mrp: 13000,
    schedule: "OTC",
    manufacturer: "Sun Pharma",
    concerns: ["everyday"],
    regimen: null,
  },
  {
    slug: "omnigel",
    brand: "Omnigel",
    molecule: "Diclofenac diethylamine + linseed oil + methyl salicylate + menthol",
    strength: "1.16%",
    form: "gel",
    packUnits: 30,
    mrp: 12500,
    schedule: "OTC",
    manufacturer: "Cipla",
    concerns: ["everyday"],
    regimen: null,
  },
  {
    slug: "combiflam",
    brand: "Combiflam",
    molecule: "Ibuprofen + paracetamol",
    strength: "400mg + 325mg",
    form: "tablet",
    packUnits: 20,
    mrp: 4600,
    schedule: "OTC",
    manufacturer: "Sanofi",
    concerns: ["everyday"],
  },
  {
    slug: "ibugesic-plus",
    brand: "Ibugesic Plus",
    molecule: "Ibuprofen + paracetamol",
    strength: "400mg + 325mg",
    form: "tablet",
    packUnits: 15,
    mrp: 3500,
    schedule: "OTC",
    manufacturer: "Cipla",
    concerns: ["everyday"],
  },
];

/** "Metformin" → "metformin", but "B-complex" and "Vitamin E" keep their capitals. */
function sentenceCase(molecule: string): string {
  const second = molecule.charAt(1);
  if (second && second === second.toLowerCase()) {
    return molecule.charAt(0).toLowerCase() + molecule.slice(1);
  }
  return molecule;
}

function describe(f: SkuFacts, about: string): string {
  const phrase = formPhrase[f.form];
  if (!phrase) return about;
  const name = sentenceCase(f.molecule);
  const what = f.strength ? `${name} ${f.strength}` : name;
  return `${f.brand} is ${what} in ${phrase}. ${about}`;
}

function build(f: SkuFacts): Sku {
  const leaflet = leaflets[f.molecule];
  if (!leaflet) throw new Error(`No leaflet for ${f.molecule}`);
  const substitutes = facts
    .filter(
      (other) =>
        other.slug !== f.slug &&
        other.molecule === f.molecule &&
        other.strength === f.strength &&
        other.form === f.form,
    )
    .map((other) => other.slug);
  const regimen = f.regimen === null ? undefined : (f.regimen ?? leaflet.regimen);

  return {
    id: f.slug,
    slug: f.slug,
    brand: f.brand,
    molecule: f.molecule,
    strength: f.strength,
    form: f.form,
    packLabel: f.pack ?? packLabel(f.packUnits, f.form),
    packUnits: f.packUnits,
    mrp: f.mrp,
    schedule: f.schedule,
    rxRequired: f.schedule !== "OTC",
    manufacturer: f.manufacturer,
    concerns: f.concerns,
    substitutes,
    description: describe(f, leaflet.about),
    howToTake: leaflet.howToTake,
    sideEffects: leaflet.sideEffects,
    warnings: leaflet.warnings,
    storage: leaflet.storage ?? defaultStorage,
    inStock: f.inStock ?? true,
    ...(regimen ? { regimen } : {}),
  };
}

export const skus: readonly Sku[] = facts.map(build);
